baseURL = "/"
languageCode = "en-us"
title = "IU Mobile"
description = "IU Mobile will focus on delivering a more holistic experience and deliver unique experiences to users of different campuses and affiliation types."
publishDir = "docs"